SEED: 1337 # random seed for reproduce results
DATA_ROOT: '/youtu-face/ata_root/remote_tfrecord' # the parent root where your train/val/test data are stored
INDEX_ROOT: '/youtu-face/train_data/'
DATASETS:  # the dataset index name
    - name: TFR-ms1m_v2_112_shuf #TFR-deepgelin_112_MS1M_Celeb_shuf
      batch_size: 128
      weight: 1.
    
BACKBONE_RESUME: "/apdcephfs/private_joejqxu/shared_info/joejqxu/task_joejqxu_2021_04_16_22_58_16_020b0299/ckpt/Backbone_Epoch_27_checkpoint.pth" #"/apdcephfs/private_joejqxu/shared_info/joejqxu/task_joejqxu_2021_01_24_16_42_16_2dad50e4/ckpt/Backbone_IR_50_Epoch_26_checkpoint.pth"
HEAD_RESUME: "/apdcephfs/private_joejqxu/shared_info/joejqxu/task_joejqxu_2021_04_16_22_58_16_020b0299/ckpt/HEAD_Epoch_27"  #"/apdcephfs/private_joejqxu/shared_info/joejqxu/task_joejqxu_2021_01_24_16_42_16_2dad50e4/ckpt/HEAD_Arcface_0_Epoch_26_"
META_RESUME: ""

BACKBONE_NAME: 'IR_101'
DIST_FC: true
TFRRECORD: true
MODEL_ROOT: './ckpt/' # the root to buffer your checkpoints
LOG_ROOT: './tensorboard' # the root to log your train/val status
HEAD_NAME: "ArcFace" # support:  ['ArcFace', 'CurricularFace', 'CosFace']
LOSS_NAME: 'DistCrossEntropy' # support: ['DistCrossEntropy', 'Softmax']
INPUT_SIZE: [112, 112] # support: [112, 112] and [224, 224]
RGB_MEAN: [0.5, 0.5, 0.5] # for normalize inputs to [-1, 1]
RGB_STD: [0.5, 0.5, 0.5]
INPUT_SIZE: [112, 112]
FC_RESUME_ROOT: "/apdcephfs/private_joejqxu/shared_info/joejqxu/ms1m_IR101_Arcface_retrain/wc.pth"
EMBEDDING_SIZE: 512 # feature dimension
LR: 0.00003 # initial LR
START_EPOCH: 0 # start epoch
WARMUP_STEP: -1
NUM_EPOCH: 27 # total epoch number
WEIGHT_DECAY: 0.0005 # do not apply to batch_norm parameters
MOMENTUM: 0.9
STAGES: [10, 16, 23] # epoch stages to decay learning rate
WORLD_SIZE: 1
RANK: 0
LOCAL_RANK: 0
DIST_BACKEND: 'nccl'
DIST_URL: 'env://'
NUM_WORKERS: 8
AMP: true # fp16 for backbone
